Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -202,11 +202,12 @@ jobs:
             done
             
             echo "Starting backup process..."
+            docker exec backup-mc backup now || echo "Couldn't call backup-mc"
             rclone sync ./mc_backups/ foo_inf:mc_backups/
             #rclone lsf foo_inf:mc_backups/ --files-only --include "*.tar.lzma" | sort | head -n -5 | xargs -I{} -r rclone deletefile foo_inf:mc_backups/{}
-            rclone delete foo_inf:mc_backups/ --min-age 6h --dry-run
-            rclone delete foo_inf:mc_backups/ --min-age 6h
-            rclone sync foo_inf:mc_backups/ ./mc_backups/
+            #rclone delete foo_inf:mc_backups/ --min-age 6h --dry-run
+            #rclone delete foo_inf:mc_backups/ --min-age 6h
+            #rclone sync foo_inf:mc_backups/ ./mc_backups/
             echo "Backup done!"
 
             cd /tmp/tqdm
